name: Deploy

on:
  release:
    types: [published]

env:
  DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: ${{ github.ref_name }}
  COMPOSE_PATH: ${{ secrets.COMPOSE_PATH }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run tests
        run: |
          go test -v ./...
          go test -race ./...

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG -t $DOCKER_REGISTRY/$IMAGE_NAME:latest -f Dockerfile .
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy or update service
        run: docker stack deploy -c $COMPOSE_PATH prod --detach=false --with-registry-auth

      - name: Clean up old images
        run: |
          docker image prune -af